# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5531441a96ad2be7ed25722c2b14ca2f7e9fb40b43830afdb0cdc26332bbb3b21b7350a2664cdd936766409bdbdd3ac669c1809ce0703a06544b67e71ade5260

test:
  secret_key_base: 3e54438163f39a1c4f7ef4421381e2eef7d7064e37fa7201454f0385dcefbac90b184550205b8cefd9d26a914d9e4161ce175bc31c2072c008a7e4f56b3dfc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
